const TopicTypes = {
  GET_TOPICS: 'GET_TOPICS',
  CREATE_TOPIC: 'CREATE_TOPIC',
  EDIT_TOPIC: 'EDIT_TOPIC',
  DELETE_TOPIC: 'DELETE_TOPIC',
  UPVOTE_TOPIC: 'UPVOTE_TOPIC',
  DOWNVOTE_TOPIC: 'DOWNVOTE_TOPIC',
};

export default TopicTypes;